### PR TITLE
update version, fix home and save folder permission issues

### PR DESCRIPTION
**Pull request by akoscomp**
I had permission problems with save folder, and in general with save folder path.
Now openttd use .local to store files indtead of .openttd folder.
With this modification this issues was fixed.

### CODE REVIEW

**Comment by bateau84** [comment]
Can you make it so that it does not break for older versions?

**Comment by bateau84** [comment]
Any response is good :sweat_smile:

**Comment by akoscomp** [comment]
Sorry, I don't observer you question.
I will test it, but probably brake later versions.

**Comment by bateau84** [comment]
Did you resolve the backwards compatibility issues here?

**Comment by akoscomp** [comment]
Now work with old and new style profile path.
I tested with 1.10.3, 1.11.2 and 12.2.
With 1.9.3 I got build error, this version can't work with your dockerfile.

**Comment by jimmypw** [comment]
Until this fix gets accepted you can work around the issue by mounting the same volume in to two locations

```
          volumeMounts:
          - name: openttd-config
            mountPath: /home/openttd/.local/share/openttd
          - name: openttd-config
            mountPath: /home/openttd/.openttd
```

**Review by bateau84 — APPROVED** [review]

**Comment by bateau84** [comment]
fixed in other PR

**Pull request closed without merging**
